# ЭТАП 1: Сборка (Build)
FROM node:18-alpine as build

WORKDIR /app

# Сначала копируем package.json, чтобы кешировать установку библиотек
COPY package.json package-lock.json ./
RUN npm install

# Копируем весь код и собираем проект
COPY . .
RUN npm run build

# ЭТАП 2: Раздача (Nginx)
FROM nginx:alpine

# Копируем конфиг nginx (создадим его ниже)
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Копируем собранные файлы из этапа build в папку Nginx
COPY --from=build /app/dist /usr/share/nginx/html

# Открываем порт 80
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]