"""Add telegram column to users

Revision ID: e1a038167e11
Revises: f690c3f05f0e
Create Date: 2026-03-11 22:40:32.919992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1a038167e11'
down_revision: Union[str, Sequence[str], None] = 'f690c3f05f0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telegram', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('birthday', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'birthday')
    op.drop_column('users', 'telegram')
    # ### end Alembic commands ###
